#!/bin/bash

BASEDIR=$(cd $(dirname $0) &>/dev/null; pwd -P)
source "$BASEDIR/lib"

if [ "$1" == "--help" ]
then
    echo "$0"
    exit 1
fi

if [ -e "$RIETVELD_DATABASE_FILE" ]
then
    echo "Rietveld database at $RIETVELD_DATABASE_FILE already exists"
    exit 1
fi

cd $BASEDIR/../rietveld/examples/rietveld || exit 1
python manage.py syncdb || exit 1

echo "Successfully created database for rietveld at $RIETVELD_DATABASE_FILE"
